### ISSUE TITLE
Unable to compile custom message for sensor_msgs/Image type 

### ISSUE THREAD

**Issue by nullbyte91** [ros2/rmw_connextdds#97]
**System Info**

- _OS_
  - Ubuntu 20.04
- *ROS version and installation type*
  - foxy 
- *RTI Connext DDS version and installation type*
  - Pro 5.3.1/apt
- *RMW version or commit hash*

**Bug Description**
I'm trying to create a custom message for the sensor msgs/Image type.
```bash
sensor_msgs/Image img
sensor_msgs/Image preprocess
```

I'm getting the following error, 
```bash
'/opt/rti.com/rti_connext_dds-5.3.1/bin/rtiddsgen_server' failed for 'perception_msg/ImageAcqusition_' with rc 255
Running non-server code generator instead...
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_typesupport_connext_cpp/__init__.py", line 71, in generate_dds_connext_cpp
    subprocess.check_call(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/rti.com/rti_connext_dds-5.3.1/bin/rtiddsgen', '-I', '~/Desktop/mygit/yolov5_deepsort_benchmarking/build/perception_msg/rosidl_generator_dds_idl', '-d', '~/Desktop/mygit/yolov5_deepsort_benchmarking/build/perception_msg/rosidl_typesupport_connext_cpp/perception_msg/msg/dds_connext', '-language', 'C++', '-namespace', '-update', 'typefiles', '-unboundedSupport', '~/Desktop/yolov5_deepsort_benchmarking/build/perception_msg/rosidl_generator_dds_idl/perception_msg/msg/dds_connext/ImageAcqusition_.idl']' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/foxy/lib/rosidl_typesupport_connext_cpp/rosidl_typesupport_connext_cpp", line 45, in <module>
    sys.exit(main())
  File "/opt/ros/foxy/lib/rosidl_typesupport_connext_cpp/rosidl_typesupport_connext_cpp", line 34, in main
    return generate_dds_connext_cpp(
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_typesupport_connext_cpp/__init__.py", line 88, in generate_dds_connext_cpp
    subprocess.check_call(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
```
**Expected Behavior**
I tried to verify the same thing with other data type and its working.
```bash
uint8[] data
```

**How to Reproduce**

[Instructions on how to reproduce the problem]

```
ros2 pkg create --build-type ament_cmake perception_msg --dependencies rclcpp std_msgs rosidl_default_generators
mkdir perception_msg/msg/ && touch perception_msg/msg/image_acqusition.msg
```
```
sensor_msgs/Image img
sensor_msgs/Image preprocess
```
CMakeList change,
```
rosidl_generate_interfaces(${PROJECT_NAME}
  "msg/ImageAcqusition.msg"
)
```
package.xml
```xml
  <depend>rosidl_default_generators</depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>
```
```bash
colcon build --packages-select perception_msg
```

**Workarounds**

**Additional context**

**Comment by clalancette** [comment]
> ros2 pkg create --build-type ament_cmake perception_msg --dependencies rclcpp std_msgs rosidl_default_generators

You are missing a dependency on `sensor_msgs`, without which this will never work.

That said, Foxy doesn't actually use `rmw_connextdds`, it uses https://github.com/ros2/rmw_connext .  So I'm going to close this out, but if adding the `sensor_msgs` dependency doesn't work, please feel free to open a new issue over thre.
